apiVersion: apps/v1
kind: Deployment
metadata:
  name: track-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: track-service
  template:
    metadata:
      labels:
        app: track-service
    spec:
      containers:
        - name: track-service-container
          image: emporion97/track-service:777
          imagePullPolicy: Always
          ports:
            - containerPort: 50052
          env:
            - name: REQUEST_TIMEOUT
              value: "10s"
            - name: CONCURRENT_LIMIT
              value: "2"
            - name: CRITICAL_LOAD
              value: "60"
