# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: track.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btrack.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0c\x63ommon.proto\"\x1c\n\x0eTrackIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"=\n\rTrackResponse\x12\x0f\n\x07trackId\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x0e\n\x06userId\x18\x03 \x01(\t\"~\n\x11TrackInfoResponse\x12\x0f\n\x07trackId\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x03 \x01(\t\x12\r\n\x05\x61lbum\x18\x04 \x01(\t\x12\r\n\x05genre\x18\x05 \x01(\t\x12\x0b\n\x03url\x18\x06 \x01(\t\x12\x0e\n\x06userId\x18\x07 \x01(\t\"L\n\x10\x45\x64itTrackRequest\x12\x0f\n\x07trackId\x18\x01 \x01(\t\x12\'\n\x08metadata\x18\x02 \x01(\x0b\x32\x15.common.TrackMetadata\"7\n\x11TrackListResponse\x12\"\n\x06tracks\x18\x01 \x03(\x0b\x32\x12.TrackInfoResponse2\xd2\x02\n\x0cTrackService\x12/\n\x06Upload\x12\x15.common.TrackMetadata\x1a\x0e.TrackResponse\x12\x32\n\x0bGetInfoById\x12\x0f.TrackIdRequest\x1a\x12.TrackInfoResponse\x12\x35\n\x08\x45\x64itInfo\x12\x11.EditTrackRequest\x1a\x16.google.protobuf.Empty\x12\x35\n\nDeleteById\x12\x0f.TrackIdRequest\x1a\x16.google.protobuf.Empty\x12\x35\n\x07\x46indAll\x12\x16.google.protobuf.Empty\x1a\x12.TrackListResponse\x12\x38\n\x06Status\x12\x16.google.protobuf.Empty\x1a\x16.common.StatusResponseB\x15Z\x13track_service/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'track_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\023track_service/proto'
  _globals['_TRACKIDREQUEST']._serialized_start=58
  _globals['_TRACKIDREQUEST']._serialized_end=86
  _globals['_TRACKRESPONSE']._serialized_start=88
  _globals['_TRACKRESPONSE']._serialized_end=149
  _globals['_TRACKINFORESPONSE']._serialized_start=151
  _globals['_TRACKINFORESPONSE']._serialized_end=277
  _globals['_EDITTRACKREQUEST']._serialized_start=279
  _globals['_EDITTRACKREQUEST']._serialized_end=355
  _globals['_TRACKLISTRESPONSE']._serialized_start=357
  _globals['_TRACKLISTRESPONSE']._serialized_end=412
  _globals['_TRACKSERVICE']._serialized_start=415
  _globals['_TRACKSERVICE']._serialized_end=753
# @@protoc_insertion_point(module_scope)
