apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  AWS_ACCESS_KEY: QUtJQVM3TTczVzRXTlhTM0lOV08=
  AWS_SECRET_KEY: SjRySHM1bFhoNG8wTnhlakoza1BDRDFLNjJaVTgrWHdCdm9YUS95ZQ==
