grpcport: ":50051"
httpport: ":8080"

dbhost: "mysql"
dbport: 3306
dbuser: "liviu"
dbpassword: "1234"
dbname: "usersdb"

jwtsecret: "pad-super-secret-key"
jwtduration: 42

requestTimeout: 5s
concurrentLimit: 5